version: "3"

networks:
  app-tier:
    driver: bridge
    
services:
  docs-app:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    networks:
      - app-tier  