version: "3"

networks:
  app-tier:
    driver: bridge
    
services:
  memgraph-mage:
    build: ./memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
    entrypoint:
      [
          "/usr/lib/memgraph/memgraph",
          "--telemetry-enabled=false",
          "--query-modules-directory=/procedures,/transformations,/usr/lib/memgraph/query_modules",
          "--log-level=TRACE",
      ]
    networks:
      - app-tier

  backend-app:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      MG_HOST: memgraph-mage
      MG_PORT: 7687
    depends_on:
      - memgraph-mage
    networks:
      - app-tier

  frontend-app:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      MG_HOST: memgraph-mage
      MG_PORT: 7687
      WATCHPACK_POLLING: true
    depends_on:
      - backend-app
    networks:
      - app-tier